#!/usr/bin/env python3
"""Generate Unicode property tables for linenoise.hpp.

Downloads the Unicode Character Database files and emits:
  - a merged codepoint range table holding the Grapheme_Cluster_Break class,
    the Extended_Pictographic flag, the Indic_Conjunct_Break class and a
    display width class for every non-default codepoint, and
  - grapheme cluster break test cases derived from GraphemeBreakTest.txt.

Usage:
  python3 scripts/gen_unicode_tables.py --update linenoise.hpp \
      --test-out test/grapheme_break_test.inc

The table section in linenoise.hpp is replaced between the markers:
  // {{{ unicode-tables (generated by scripts/gen_unicode_tables.py ...)
  // }}} unicode-tables

Hangul syllables (U+AC00..U+D7A3) are intentionally excluded from the table:
their LV/LVT class and width are computed algorithmically in C++.
"""

import argparse
import os
import re
import sys
import urllib.request

UCD_BASE = "https://www.unicode.org/Public/UCD/latest/ucd/"
FILES = {
    "GraphemeBreakProperty.txt": "auxiliary/GraphemeBreakProperty.txt",
    "GraphemeBreakTest.txt": "auxiliary/GraphemeBreakTest.txt",
    "emoji-data.txt": "emoji/emoji-data.txt",
    "DerivedCoreProperties.txt": "DerivedCoreProperties.txt",
    "EastAsianWidth.txt": "EastAsianWidth.txt",
    "DerivedGeneralCategory.txt": "extracted/DerivedGeneralCategory.txt",
    "ReadMe.txt": "ReadMe.txt",
}

MAX_CP = 0x110000
HANGUL_SYL_FIRST = 0xAC00
HANGUL_SYL_LAST = 0xD7A3

# Grapheme_Cluster_Break classes. Must match the C++ enum.
GCB = {
    "Other": 0,
    "CR": 1,
    "LF": 2,
    "Control": 3,
    "Extend": 4,
    "ZWJ": 5,
    "Regional_Indicator": 6,
    "Prepend": 7,
    "SpacingMark": 8,
    "L": 9,
    "V": 10,
    "T": 11,
    "LV": 12,
    "LVT": 13,
}

# Indic_Conjunct_Break classes. Must match the C++ enum.
INCB = {"None": 0, "Consonant": 1, "Extend": 2, "Linker": 3}

# Width classes. Must match the C++ enum.
WIDTH_DEFAULT = 0  # 1 column
WIDTH_ZERO = 1     # 0 columns
WIDTH_WIDE = 2     # 2 columns

EXTPICT_BIT = 1 << 4
INCB_SHIFT = 5
WIDTH_SHIFT = 7


def fetch(cache_dir, name):
    path = os.path.join(cache_dir, name)
    if not os.path.exists(path):
        url = UCD_BASE + FILES[name]
        print(f"downloading {url}", file=sys.stderr)
        os.makedirs(cache_dir, exist_ok=True)
        with urllib.request.urlopen(url) as r, open(path, "wb") as f:
            f.write(r.read())
    with open(path, encoding="utf-8") as f:
        return f.read()


def parse_cp_range(cps):
    """Parse 'XXXX' or 'XXXX..YYYY' into (lo, hi)."""
    if ".." in cps:
        lo, hi = (int(x, 16) for x in cps.split(".."))
        return lo, hi
    cp = int(cps, 16)
    return cp, cp


def parse_props(text):
    """Yield (lo, hi, value) from a UCD property file."""
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        lo, hi = parse_cp_range(fields[0])
        yield lo, hi, fields[1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--update", metavar="HPP", help="update table section in this header")
    ap.add_argument("--test-out", metavar="INC", help="write grapheme break test cases here")
    ap.add_argument("--cache", default=".ucd-cache", help="UCD download cache directory")
    args = ap.parse_args()

    cache = args.cache
    version = "unknown"
    m = re.search(r"Version (\d+\.\d+\.\d+)", fetch(cache, "ReadMe.txt"))
    if m:
        version = m.group(1)

    gcb = bytearray(MAX_CP)       # GCB class per codepoint
    extpict = bytearray(MAX_CP)   # Extended_Pictographic flag
    incb = bytearray(MAX_CP)      # InCB class per codepoint
    width = bytearray(MAX_CP)     # width class per codepoint

    for lo, hi, val in parse_props(fetch(cache, "GraphemeBreakProperty.txt")):
        if val in GCB:
            for cp in range(lo, hi + 1):
                gcb[cp] = GCB[val]

    for lo, hi, val in parse_props(fetch(cache, "emoji-data.txt")):
        if val == "Extended_Pictographic":
            for cp in range(lo, hi + 1):
                extpict[cp] = 1

    default_ignorable = bytearray(MAX_CP)
    for lo, hi, val in parse_props(fetch(cache, "DerivedCoreProperties.txt")):
        if val == "InCB":
            # DerivedCoreProperties lists InCB as "cp; InCB; <class>"
            continue
        if val == "Default_Ignorable_Code_Point":
            for cp in range(lo, hi + 1):
                default_ignorable[cp] = 1
    for line in fetch(cache, "DerivedCoreProperties.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        if len(fields) >= 3 and fields[1] == "InCB":
            lo, hi = parse_cp_range(fields[0])
            for cp in range(lo, hi + 1):
                incb[cp] = INCB[fields[2]]

    gencat = {}
    for lo, hi, val in parse_props(fetch(cache, "DerivedGeneralCategory.txt")):
        if val in ("Mn", "Me", "Cf"):
            for cp in range(lo, hi + 1):
                gencat[cp] = val

    eaw_wide = bytearray(MAX_CP)
    for lo, hi, val in parse_props(fetch(cache, "EastAsianWidth.txt")):
        if val in ("W", "F"):
            for cp in range(lo, hi + 1):
                eaw_wide[cp] = 1
    # Default East_Asian_Width is W for these unassigned/CJK-reserved planes
    # (see the @missing declarations in EastAsianWidth.txt).
    for lo, hi in ((0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF),
                   (0x20000, 0x2FFFD), (0x30000, 0x3FFFD)):
        for cp in range(lo, hi + 1):
            eaw_wide[cp] = 1

    # Compose display width class.
    for cp in range(MAX_CP):
        if cp == 0x00AD:  # soft hyphen: 1 column by wcwidth() convention
            width[cp] = WIDTH_DEFAULT
        elif gencat.get(cp) in ("Mn", "Me", "Cf") or default_ignorable[cp]:
            width[cp] = WIDTH_ZERO
        elif gcb[cp] in (GCB["V"], GCB["T"]):
            # Conjoining Hangul jamo vowels/trailing consonants combine into
            # the preceding syllable block: 0 columns.
            width[cp] = WIDTH_ZERO
        elif eaw_wide[cp]:
            width[cp] = WIDTH_WIDE

    # Merge into one value per codepoint, skipping the algorithmic Hangul
    # syllable range.
    entries = []  # (lo, hi, val)
    prev_val = 0
    run_start = None
    for cp in range(MAX_CP + 1):
        if cp < MAX_CP and HANGUL_SYL_FIRST <= cp <= HANGUL_SYL_LAST:
            val = 0
        elif cp < MAX_CP:
            val = (gcb[cp] | (EXTPICT_BIT if extpict[cp] else 0) |
                   (incb[cp] << INCB_SHIFT) | (width[cp] << WIDTH_SHIFT))
        else:
            val = 0
        if val != prev_val:
            if prev_val != 0:
                entries.append((run_start, cp - 1, prev_val))
            run_start = cp
            prev_val = val

    lines = []
    lines.append(f"// Unicode {version}. {len(entries)} ranges.")
    lines.append("inline const CharProp char_props[] = {")
    row = []
    for lo, hi, val in entries:
        row.append(f"{{0x{lo:X},0x{hi:X},0x{val:X}}},")
        if len(row) == 4:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("};")
    lines.append(f"inline constexpr size_t char_props_size = {len(entries)};")
    table_text = "\n".join(lines)

    if args.update:
        with open(args.update, encoding="utf-8") as f:
            src = f.read()
        begin = "// {{{ unicode-tables"
        end = "// }}} unicode-tables"
        begin_at = src.index(begin)
        j = src.index(end)
        marker = (f"// {{{{{{ unicode-tables (generated by "
                  f"scripts/gen_unicode_tables.py, Unicode {version})\n")
        src = src[:begin_at] + marker + table_text + "\n" + src[j:]
        with open(args.update, "w", encoding="utf-8") as f:
            f.write(src)
        print(f"updated {args.update} ({len(entries)} ranges, Unicode {version})",
              file=sys.stderr)
    else:
        print(table_text)

    if args.test_out:
        cases = []
        for line in fetch(cache, "GraphemeBreakTest.txt").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            # Format: ÷ 0020 × 0308 ÷ 0020 ÷
            toks = line.split()
            cps, breaks = [], []  # breaks: indexes into cps where a cluster starts
            for tok in toks:
                if tok == "÷":
                    breaks.append(len(cps))
                elif tok == "×":
                    pass
                else:
                    cps.append(int(tok, 16))
            # Final ÷ marks end of text; keep it (== len(cps)).
            cases.append((cps, breaks))
        out = []
        out.append("// Generated by scripts/gen_unicode_tables.py from")
        out.append(f"// GraphemeBreakTest.txt (Unicode {version}). Do not edit.")
        out.append("struct GraphemeBreakCase {")
        out.append("    std::vector<uint32_t> cps;")
        out.append("    std::vector<size_t> breaks; // cluster start indexes + end")
        out.append("};")
        out.append("inline const std::vector<GraphemeBreakCase> grapheme_break_cases = {")
        for cps, breaks in cases:
            c = ",".join(f"0x{x:X}" for x in cps)
            b = ",".join(str(x) for x in breaks)
            out.append(f"    {{{{{c}}},{{{b}}}}},")
        out.append("};")
        os.makedirs(os.path.dirname(args.test_out), exist_ok=True)
        with open(args.test_out, "w", encoding="utf-8") as f:
            f.write("\n".join(out) + "\n")
        print(f"wrote {args.test_out} ({len(cases)} cases)", file=sys.stderr)


if __name__ == "__main__":
    main()
